In [1]:
import numpy as np

test_1 = np.array([92, 94, 88, 91, 87])
print(test_1)

[92 94 88 91 87]


In [5]:
import numpy as np
import os


test_1 = np.array([92, 94, 88, 91, 87])

#We want to load the data from test_2.csv and store it in an array called test_2
test_2 = np.genfromtxt('test_2.csv', delimiter=',')
print(os.getcwd())

test_2


/Users/logambigaikuppusamy/Documents/DataScience/Financeanalyst


/var/folders/fk/20jflc4n4z32_r921kfz_l8h0000gn/T/ipykernel_12441/734391840.py:8: UserWarning: genfromtxt: Empty input file: "test_2.csv"
  test_2 = np.genfromtxt('test_2.csv', delimiter=',')


array([], dtype=float64)

In [10]:
# With a list
l = [1, 2, 3, 4, 5]
l_plus_3 = []
for i in range(len(l)):
    l_plus_3.append(l[i] + 3)

print(l_plus_3)

# With an array
a = np.array(l)
a_plus_3 = a + 3
print(a_plus_3)

a ** 2 #array([ 1,  4,  9, 16, 25, 36])
np.sqrt(a_plus_3)

[4, 5, 6, 7, 8]
[4 5 6 7 8]


array([2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712])

In [11]:
import numpy as np

test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

# method 1
# test_3_fixed = []
# for i in range(len(test_3)):
#     test_3_fixed.append(test_3[i]+2)

test_3_fixed = test_3 + 2
print(test_3_fixed)

[89 87 74 92 94]


In [13]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
a + b     #array([ 7,  9, 11, 13, 15])

array([ 7,  9, 11, 13, 15])

In [14]:
import numpy as np

test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])
test_3_fixed = test_3 + 2

total_grade = test_1 + test_2 + test_3_fixed
print(total_grade)

final_grade = total_grade / 3
print(final_grade)

[260 281 248 276 272]
[86.66666667 93.66666667 82.66666667 92.         90.66666667]


In [15]:
# Two Dimensional Array
import numpy as np

coin_toss = np.array([1, 0, 0, 1, 0])
coin_toss_again = np.array([[1, 0, 0, 1, 0], [0, 0, 1, 1, 1]])
coin_toss_again

array([[1, 0, 0, 1, 0],
       [0, 0, 1, 1, 1]])

In [19]:
import numpy as np

test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

jeremy_test_2 = test_2[3]
print(jeremy_test_2)

manual_adwoa_test_1 = test_1[1:3]
print(manual_adwoa_test_1)

93
[94 88]


In [32]:
# two dimensional array
import numpy as np

student_scores = np.array([[92, 94, 88, 91, 87],[79, 100, 86, 93, 91],[87, 85, 72, 90, 92]])
print(student_scores[2,1])
print(student_scores[:,0]) # returns 0th index value from each inner array
print(student_scores[0,2:5]) # This prints elements from positions 2, 3, and 4 of the first row in the array
print(student_scores[1,3:5]) # This prints elements from positions 2, 3, and 4 of the second row in the array
print(student_scores[2,1:4]) # This prints elements from positions 2, 3, and 4 of the second row in the array

85
[92 79 87]
[88 91 87]
[93 91]
[85 72 90]


In [33]:
import numpy as np

student_scores = np.array([[92, 94, 88, 91, 87],[79, 100, 86, 93, 91],[87, 85, 72, 90, 92]])

tanya_test_3 = student_scores[2,0] # select tanya score from test3
print(tanya_test_3)

cody_test_scores = student_scores[:,4]
print(cody_test_scores)

87
[87 91 92]


In [36]:
# Logical operator with Arrays
a = np.array([10, 2, 2, 4, 5, 3, 9, 8, 9, 7])
a>5 # output -array([ True, False, False, False, False, False,  True,  True,  True,True])
a[a>5] # output array([10,  9,  8,  9,  7])

array([10,  9,  8,  9,  7])

In [ ]:
import numpy as np

porridge = np.array([79, 65, 50, 63, 56, 90, 85, 98, 79, 51])

cold = porridge[porridge< 60]
print(cold)

hot = porridge[porridge >80]
print(hot)

just_right = porridge[(porridge>60) & (porridge<=80)]
print(just_right)

In [ ]:
#Project 1

import numpy as np
temperatures = np.genfromtxt('temperature_data.csv', delimiter=',')

print(temperatures)

temperatures_fixed = temperatures + 3

print(temperatures_fixed)

monday_temperatures = temperatures_fixed[0,:]

thursday_friday_morning = temperatures_fixed[3:5,1]

temperature_extremes = temperatures_fixed[(temperatures_fixed < 50) | (temperatures_fixed > 60)]

print(monday_temperatures)
print(thursday_friday_morning)
print(temperature_extremes)

In [ ]:
#Betty's Bakery

import numpy as np
cupcakes = np.array([2, 0.75, 2, 1, 0.5])

# Betty’s assistant has compiled all of her recipes into a csv (comma-separated variable) file called recipes.csv

recipes = np.genfromtxt('recipes.csv', delimiter=",")
print(recipes)

# 3rd column represents the number of eggs that each recipe needs
eggs = recipes[:,2]
print(eggs)

# Which recipes require exactly 1 egg
print(eggs==1)

#  1 batch of cookies (3rd row)
cookies = recipes[3,:]
print(cookies)

# Get the number of ingredients for a double batch of cupcakes by using multiplication on cupcakes
double_batch = cupcakes *2
print(double_batch)